version: '3.8'
services:
  redis-container:
    image: redis:alpine
    networks:
      - app-net
    ports:
      - 6379:6379

  mysql-container:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: account_db pic_db
    networks:
      - app-net
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d

  account-backend:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - redis-container
      - mysql-container
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
